# Generated by Django 3.1.7 on 2021-03-24 17:25
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
