# Generated by Django 4.2.21 on 2025-09-11 15:38
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("app_six", "0001_initial"),
        ("app_six", "0002_app_six"),
        ("app_six", "0003_app_six"),
        ("app_six", "0004_app_six"),
        ("app_six", "0005_app_six"),
        ("app_six", "0006_app_six"),
        ("app_six", "0007_app_six"),
        ("app_six", "0008_app_six"),
        ("app_six", "0009_app_six"),
        ("app_six", "0010_app_six"),
        ("app_six", "0011_app_six"),
        ("app_six", "0012_app_six"),
        ("app_six", "0013_app_six"),
        ("app_six", "0014_app_six"),
        ("app_six", "0015_app_six"),
        ("app_six", "0016_app_six"),
        ("app_six", "0017_app_six"),
        ("app_six", "0018_app_six"),
        ("app_six", "0019_app_six"),
        ("app_six", "0020_app_six"),
        ("app_six", "0021_app_six"),
        ("app_six", "0022_app_six"),
        ("app_six", "0023_app_six"),
        ("app_six", "0024_app_six"),
        ("app_six", "0025_app_six"),
        ("app_six", "0026_app_six"),
        ("app_six", "0027_app_six"),
        ("app_six", "0028_app_six"),
        ("app_six", "0029_app_six"),
        ("app_six", "0027_app_six_2"),
        ("app_six", "0030_app_six"),
        ("app_six", "0031_app_six"),
        ("app_six", "0032_app_six"),
        (
            "app_six",
            "0033_app_six",
        ),
        ("app_six", "0034_app_six"),
        ("app_six", "0035_app_six"),
        ("app_six", "0036_app_six"),
        ("app_six", "0037_app_six"),
        ("app_six", "0038_app_six"),
        ("app_six", "0039_app_six"),
        ("app_six", "0040_app_six"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelNine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ModelTen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ModelEleven",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ModelTwelve",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
    ]
