# Generated by Django 3.1.7 on 2021-03-26 21:57
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0001_initial"),
    ]

    operations = []
