# Generated by Django 3.1.7 on 2021-03-29 23:00
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0002_app_six"),
    ]

    operations = []
