# Generated by Django 3.1.8 on 2021-05-12 14:12
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0003_app_six"),
    ]

    operations = []
