# Generated by Django 3.1.8 on 2021-05-12 20:37
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0004_app_six"),
    ]

    operations = []
