# Generated by Django 3.1.11 on 2021-05-13 18:40
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("auth", "0012_alter_user_first_name_max_length"),
        ("app_six", "0005_app_six"),
        # ("app_thirteen", "0011_auto_20210512_1452"),
        # ("users", "0009_modify_group_can_review_project_tasks"),
    ]

    operations = []
