# Generated by Django 3.1.12 on 2021-06-08 18:20
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_six", "0006_app_six"),
    ]

    operations = []
