# Generated by Django 3.1.13 on 2021-11-16 18:20
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0007_app_six"),
    ]

    operations = []
