# Generated by Django 3.1.13 on 2021-12-06 22:24
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0010_app_six"),
    ]

    operations = []
