# Generated by Django 3.1.13 on 2021-12-08 20:04
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0012_app_six"),
    ]

    operations = []
