# Generated by Django 3.1.13 on 2022-01-11 20:35
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0013_app_six"),
    ]

    operations = []
