# Generated by Django 3.1.13 on 2022-01-12 20:04
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0014_app_six"),
    ]

    operations = []
