# Generated by Django 3.1.13 on 2022-01-17 18:26
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_six", "0015_app_six"),
    ]

    operations = []
