# Generated by Django 3.1.13 on 2022-01-12 22:52
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0017_app_six"),
    ]

    operations = []
