# Generated by Django 3.1.13 on 2022-01-13 20:02
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0018_app_six"),
    ]

    operations = []
