# Generated by Django 3.1.14 on 2022-01-24 22:50
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0019_app_six"),
    ]

    operations = []
