# Generated by Django 3.1.14 on 2022-01-26 20:01
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0020_app_six"),
    ]

    operations = []
