# Generated by Django 3.1.14 on 2022-01-31 22:36
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0022_app_six"),
    ]

    operations = []
