# Generated by Django 3.1.14 on 2022-02-22 17:23
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0023_app_six"),
    ]

    operations = []
