# Generated by Django 3.2.13 on 2022-06-27 18:19
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0025_app_six"),
    ]

    operations = []
