# Generated by Django 3.2.14 on 2022-07-14 22:54
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0026_app_six"),
    ]

    operations = []
