# Generated by Django 3.2.14 on 2022-07-15 17:05
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0028_app_six"),
    ]

    operations = []
