# Generated by Django 3.2.14 on 2022-07-27 17:00
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0027_app_six_2"),
        ("app_six", "0029_app_six"),
    ]

    operations = []
