# Generated by Django 3.2.15 on 2022-08-22 21:04
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0030_app_six"),
    ]

    operations = []
