# Generated by Django 3.2.15 on 2022-08-23 20:11
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0031_app_six"),
    ]

    operations = []
