# Generated by Django 3.2.15 on 2022-10-03 22:42
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0032_app_six"),
    ]

    operations = []
