# Generated by Django 3.2.19 on 2023-08-11 17:26
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0034_app_six"),
    ]

    operations = []
