# Generated by Django 4.2.13 on 2024-09-12 15:50
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0036_app_six"),
    ]

    operations = []
