# Generated by Django 4.2.17 on 2025-01-29 23:35
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0038_app_six"),
    ]

    operations = []
