# Generated by Django 4.2.21 on 2025-06-27 19:59
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_six", "0039_app_six"),
    ]

    operations = []
