# Generated by Django 4.2.21 on 2025-09-12 16:05
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("app_eighteen", "0001_initial"),
        ("app_eighteen", "0002_app_eighteen"),
        ("app_eighteen", "0003_app_eighteen"),
        (
            "app_eighteen",
            "0004_app_eighteen",
        ),
        ("app_eighteen", "0005_app_eighteen"),
        ("app_eighteen", "0006_app_eighteen"),
        ("app_eighteen", "0007_app_eighteen"),
        ("app_eighteen", "0008_app_eighteen"),
        ("app_eighteen", "0009_app_eighteen"),
        ("app_eighteen", "0010_app_eighteen"),
        ("app_eighteen", "0011_app_eighteen"),
        ("app_eighteen", "0012_app_eighteen"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelFiftyThree",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ModelFiftyFour",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ModelFiftyFive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
    ]
