# Generated by Django 3.1.11 on 2021-05-25 22:01
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # ("users", "0012_update_task_code_manager_with_software"),
        ("app_thirteen", "0014_app_thirteen"),
    ]

    operations = []
