# Generated by Django 3.1.11 on 2021-05-25 23:37
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_eighteen", "0002_app_eighteen"),
    ]

    operations = []
