# Generated by Django 3.1.12 on 2021-06-14 19:58
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_twelve", "0013_auto_20210609_1110"),
        # ("app_seventeen", "0024_historicaltimesheet_historicaltimesheettask"),
        (
            "app_eighteen",
            "0004_app_eighteen",
        ),
    ]

    operations = []
