# Generated by Django 3.1.12 on 2021-06-14 20:08
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_eighteen", "0005_app_eighteen"),
    ]

    operations = []
