# Generated by Django 3.1.12 on 2021-06-14 21:31
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_eighteen", "0006_app_eighteen"),
    ]

    operations = []
