# Generated by Django 3.1.12 on 2021-06-14 23:28
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_one", "0003_historicalmodelone"),
        # ("app_twelve", "0013_auto_20210609_1110"),
        # ("app_fifteen", "0011_reviewedtasksnotification_email"),
        # ("app_seventeen", "0025_auto_20210614_1422"),
        ("app_eighteen", "0007_app_eighteen"),
    ]

    operations = []
