# Generated by Django 3.1.12 on 2021-06-16 21:18
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_eighteen", "0009_app_eighteen"),
    ]

    operations = []
