# Generated by Django 3.2.22 on 2023-12-08 18:18
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_eighteen", "0011_app_eighteen"),
    ]

    operations = []
