# Generated by Django 3.1.8 on 2021-04-07 15:56
from django.db import migrations

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # ("app_six", "0003_auto_20210329_1700"),
    ]

    operations = []
