# Generated by Django 4.2.21 on 2025-09-11 22:14
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("app_seventeen", "0001_initial"),
        ("app_seventeen", "0002_app_seventeen"),
        ("app_seventeen", "0003_app_seventeen"),
    ]

    dependencies = [
        ("app_seventeen", "0001_squashed_initial"),
    ]

    run_before = []

    operations = []
