# Generated by Django 3.1.8 on 2021-04-07 16:52
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0001_initial"),
    ]

    operations = []
