# Generated by Django 3.1.8 on 2021-04-07 23:32
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_six", "0003_auto_20210329_1700"),
        ("app_seventeen", "0002_app_seventeen"),
    ]

    operations = []
