# Generated by Django 3.1.8 on 2021-04-08 17:00
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0005_app_seventeen"),
    ]

    operations = []
