# Generated by Django 3.1.8 on 2021-04-08 17:31
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_thirteen", "0001_initial"),
        ("app_seventeen", "0006_app_seventeen"),
    ]

    operations = []
