# Generated by Django 3.1.8 on 2021-04-13 19:27
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0007_app_seventeen"),
    ]

    operations = []
