# Generated by Django 3.1.8 on 2021-04-19 20:29
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0010_app_seventeen"),
    ]

    operations = []
