# Generated by Django 3.1.8 on 2021-05-04 00:30
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0012_app_seventeen"),
    ]

    operations = []
