# Generated by Django 3.1.8 on 2021-05-04 17:41
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0014_app_seventeen_2"),
    ]

    operations = []
