# Generated by Django 3.1.8 on 2021-05-04 23:11
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_twelve", "0003_auto_20210430_1232"),
        ("app_seventeen", "0015_app_seventeen_2"),
    ]

    operations = []
