# Generated by Django 3.1.8 on 2021-05-04 17:43
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0015_app_seventeen"),
    ]

    operations = []
