# Generated by Django 3.1.8 on 2021-05-04 23:38
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0016_app_seventeen"),
        ("app_seventeen", "0016_app_seventeen_2"),
    ]

    operations = []
