# Generated by Django 3.1.8 on 2021-05-11 17:06
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0018_app_seventeen"),
    ]

    operations = []
