# Generated by Django 3.1.11 on 2021-05-15 16:05
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0020_app_seventeen"),
    ]

    operations = []
