# Generated by Django 3.1.11 on 2021-05-25 16:37
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0021_app_seventeen"),
        # ("app_eighteen", "0003_auto_20210525_1737"),
    ]

    operations = []
