# Generated by Django 3.1.12 on 2021-06-08 18:20
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_thirteen", "0016_historicalproject"),
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ("app_six", "0007_historicalemployee"),
        # ("app_eighteen", "0004_historicalsoftware_historicalworkactivity_historicalworkcategory"),
        # (
        #     "app_twelve",
        #     "0011_historicalphase_historicalprojectactivity_historicalprojectcategory_historicalprojectworkactivity",
        # ),
        ("app_seventeen", "0023_app_seventeen"),
    ]

    operations = []
