# Generated by Django 3.1.12 on 2021-06-14 20:22
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_eighteen", "0006_auto_20210614_1408"),
        ("app_seventeen", "0024_app_seventeen"),
    ]

    operations = []
