# Generated by Django 3.1.12 on 2021-06-23 15:55
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_seventeen", "0025_app_seventeen"),
    ]

    operations = []
