# Generated by Django 3.1.12 on 2021-06-24 18:37
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0026_app_seventeen"),
    ]

    operations = []
