# Generated by Django 3.1.13 on 2021-07-06 23:26
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0027_app_seventeen"),
    ]

    operations = []
