# Generated by Django 3.1.13 on 2021-07-08 15:35
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0028_app_seventeen"),
    ]

    operations = []
