# Generated by Django 3.1.13 on 2021-07-21 17:39
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0030_app_seventeen"),
    ]

    operations = []
