# Generated by Django 3.1.13 on 2021-08-13 17:15
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_eight", "0004_create_intial_employeestats"),
        ("app_seventeen", "0031_app_seventeen"),
    ]

    operations = []
