# Generated by Django 3.1.13 on 2021-08-13 17:16
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0032_app_seventeen"),
    ]

    operations = []
