# Generated by Django 3.1.14 on 2022-01-31 19:13
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0034_app_seventeen"),
    ]

    operations = []
