# Generated by Django 3.2.13 on 2022-06-14 20:37
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0035_app_seventeen"),
    ]

    operations = []
