# Generated by Django 3.2.13 on 2022-06-14 20:38
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0036_app_seventeen"),
        # ("app_four", "0004_auto_20220615_1519"),
        # ("app_nine", "0013_alter_timesheetsimport_pay_period_ending"),
        # ("app_eleven", "0009_alter_recentlyapprovedreportdownload_pay_period_ending"),
    ]

    operations = []
