# Generated by Django 3.2.13 on 2022-06-15 22:21
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0038_app_seventeen"),
    ]

    operations = []
