# Generated by Django 3.2.13 on 2022-07-05 20:23
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_six", "0026_add_employement_type_to_employment_range"),
        ("app_seventeen", "0039_app_seventeen"),
    ]

    operations = []
