# Generated by Django 3.2.13 on 2022-07-06 21:13
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0041_app_seventeen"),
    ]

    operations = []
