# Generated by Django 3.2.14 on 2022-07-15 19:05
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0044_app_seventeen"),
    ]

    operations = []
