# Generated by Django 3.2.14 on 2022-07-19 15:36
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0045_app_seventeen"),
    ]

    operations = []
