# Generated by Django 3.2.15 on 2022-09-08 21:00
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0047_app_seventeen"),
    ]

    operations = []
