# Generated by Django 3.2.16 on 2022-12-16 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0049_app_seventeen"),
        ("app_seventeen", "0049_app_seventeen_2"),
    ]

    operations = []
