# Generated by Django 3.2.22 on 2023-10-18 22:41
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0050_app_seventeen"),
    ]

    operations = []
