# Generated by Django 4.2.11 on 2024-05-17 20:57
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0051_app_seventeen"),
    ]

    operations = []
