# Generated by Django 4.2.18 on 2025-03-18 20:17
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0053_app_seventeen"),
    ]

    operations = []
