# Generated by Django 4.2.21 on 2025-08-22 17:00
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0054_app_seventeen"),
    ]

    operations = []
