# Generated by Django 4.2.21 on 2025-08-22 19:04
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0056_app_seventeen"),
    ]

    operations = []
