# Generated by Django 4.2.21 on 2025-08-26 18:45
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seventeen", "0057_app_seventeen"),
    ]

    operations = []
