# Generated by Django 3.1.13 on 2021-09-16 17:26
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
