# Generated by Django 4.2.21 on 2025-09-11 15:27
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("app_four", "0001_initial"),
        ("app_four", "0002_app_four"),
        ("app_four", "0003_app_four"),
        ("app_four", "0004_app_four"),
        ("app_four", "0005_app_four"),
        ("app_four", "0006_app_four"),
        ("app_four", "0007_app_four"),
        ("app_four", "0008_app_four"),
        ("app_four", "0009_app_four_2"),
        ("app_four", "0010_app_four"),
        ("app_four", "0009_app_four"),
        ("app_four", "0011_app_four"),
        (
            "app_four",
            "0012_app_four",
        ),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_seventeen", "0003_squashed_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelSeven",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
    ]
