# Generated by Django 3.1.13 on 2021-09-16 19:11
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_four", "0001_initial"),
    ]

    operations = []
