# Generated by Django 3.2.13 on 2022-06-14 20:37
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_seventeen", "0036_auto_20220614_1437"),
        ("app_four", "0002_app_four"),
    ]

    operations = []
