# Generated by Django 3.2.13 on 2022-06-15 21:19
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_four", "0003_app_four"),
    ]

    operations = []
