# Generated by Django 3.2.14 on 2022-07-11 17:23
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_seventeen", "0043_alter_timesheettask_pay_period"),
        ("app_four", "0004_app_four"),
    ]

    operations = []
