# Generated by Django 3.2.15 on 2022-09-07 21:27
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_seventeen", "0046_auto_20220719_0936"),
        ("app_four", "0005_app_four"),
    ]

    operations = []
