# Generated by Django 3.2.15 on 2022-09-07 21:28
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_four", "0006_app_four"),
    ]

    operations = []
