# Generated by Django 3.2.16 on 2022-10-04 23:07
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_four", "0008_app_four"),
    ]

    operations = []
