# Generated by Django 3.2.16 on 2022-12-16 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_four", "0009_app_four"),
        ("app_four", "0010_app_four"),
    ]

    operations = []
