# Generated by Django 4.2.11 on 2024-05-28 19:58
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_four", "0011_app_four"),
    ]

    operations = []
