# Generated by Django 3.1.13 on 2021-11-15 22:18
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_seventeen", "0033_app_seventeen"),
    ]

    operations = []
