# Generated by Django 4.2.21 on 2025-09-11 17:09

import django
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("app_nine", "0001_initial"),
        ("app_nine", "0002_app_nine"),
        ("app_nine", "0003_app_nine"),
        ("app_nine", "0004_app_nine"),
        ("app_nine", "0005_app_nine"),
        ("app_nine", "0006_app_nine"),
        ("app_nine", "0007_app_nine"),
        ("app_nine", "0008_app_nine"),
        ("app_nine", "0009_app_nine"),
        ("app_nine", "0010_app_nine"),
        ("app_nine", "0011_app_nine"),
        ("app_nine", "0012_app_nine"),
        ("app_nine", "0013_app_nine"),
        ("app_nine", "0014_app_nine"),
        ("app_nine", "0015_app_nine_2"),
        ("app_nine", "0015_app_nine"),
        ("app_nine", "0016_app_nine"),
        ("app_nine", "0017_app_nine"),
        (
            "app_nine",
            "0018_app_nine",
        ),
        ("app_nine", "0019_app_nine"),
        (
            "app_nine",
            "0020_app_nine",
        ),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_six", "0001_squashed_initial"),
        ("app_thirteen", "0001_squashed_initial"),
        ("app_seventeen", "0001_squashed_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelFifteen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ModelEighteen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ModelSeventeen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ModelSixteen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ModelNineteen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
    ]
