# Generated by Django 3.1.13 on 2021-11-16 00:10
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_nine", "0001_initial"),
    ]

    operations = []
