# Generated by Django 3.1.13 on 2021-11-16 23:42
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_thirteen", "0022_populate_australian_and_non_billable_projects"),
        # ("app_six", "0009_populate_employee_service_codes"),
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_nine", "0002_app_nine"),
    ]

    operations = []
