# Generated by Django 3.1.13 on 2021-11-17 21:54
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_nine", "0003_app_nine"),
    ]

    operations = []
