# Generated by Django 3.1.13 on 2021-11-19 17:14
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_nine", "0004_app_nine"),
    ]

    operations = []
