# Generated by Django 3.1.13 on 2021-11-23 22:47
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_nine", "0005_app_nine"),
    ]

    operations = []
