# Generated by Django 3.1.13 on 2021-11-24 21:24
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_nine", "0008_app_nine"),
    ]

    operations = []
