# Generated by Django 3.1.13 on 2021-12-06 18:58
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_six", "0009_populate_employee_service_codes"),
        # ("app_fourteen", "0003_auto_20211206_1158"),
        # ("app_thirteen", "0022_populate_australian_and_non_billable_projects"),
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_nine", "0009_app_nine"),
    ]

    operations = []
