# Generated by Django 3.2.15 on 2022-09-16 18:01
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_nine", "0014_app_nine"),
    ]

    operations = []
