# Generated by Django 3.2.16 on 2022-12-16 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_nine", "0015_app_nine"),
        ("app_nine", "0015_app_nine_2"),
    ]

    operations = []
