# Generated by Django 4.2.11 on 2024-04-12 17:26
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_seventeen", "0051_auto_20231018_1641"),
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_nine", "0016_app_nine"),
    ]

    operations = []
