# Generated by Django 4.2.21 on 2025-09-04 16:20
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_nine", "0019_app_nine"),
    ]

    operations = []
