# Generated by Django 3.1.11 on 2021-06-02 00:17
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # ("app_fifteen", "0010_reviewedtasksnotification"),
    ]

    operations = []
