# Generated by Django 3.1.11 on 2021-06-02 18:05
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_three", "0001_initial"),
    ]

    operations = []
