# Generated by Django 3.1.12 on 2021-06-22 18:10
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_three", "0005_app_three"),
    ]

    operations = []
