# Generated by Django 4.2.21 on 2025-09-11 20:39
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("app_fifteen", "0001_initial"),
        ("app_fifteen", "0002_app_fifteen"),
        ("app_fifteen", "0003_app_fifteen"),
        ("app_fifteen", "0004_app_fifteen"),
        ("app_fifteen", "0005_app_fifteen"),
        ("app_fifteen", "0006_app_fifteen"),
        ("app_fifteen", "0007_app_fifteen"),
        ("app_fifteen", "0008_app_fifteen"),
        ("app_fifteen", "0009_app_fifteen"),
        ("app_fifteen", "0010_app_fifteen"),
        ("app_fifteen", "0011_app_fifteen"),
        ("app_fifteen", "0012_app_fifteen"),
        ("app_fifteen", "0013_app_fifteen"),
        ("app_fifteen", "0014_app_fifteen"),
        ("app_fifteen", "0015_app_fifteen"),
        ("app_fifteen", "0016_app_fifteen"),
        ("app_fifteen", "0017_app_fifteen"),
        ("app_fifteen", "0018_app_fifteen"),
        ("app_fifteen", "0019_app_fifteen"),
        ("app_fifteen", "0020_app_fifteen"),
        ("app_fifteen", "0021_app_fifteen"),
        ("app_fifteen", "0022_app_fifteen"),
        ("app_fifteen", "0023_app_fifteen"),
        ("app_fifteen", "0024_app_fifteen"),
        ("app_fifteen", "0025_app_fifteen"),
        ("app_fifteen", "0026_app_fifteen"),
        ("app_fifteen", "0027_app_fifteen"),
        (
            "app_fifteen",
            "0028_app_fifteen_2",
        ),
        ("app_fifteen", "0028_app_fifteen"),
        ("app_fifteen", "0029_app_fifteen"),
        ("app_fifteen", "0030_app_fifteen"),
        ("app_fifteen", "0031_app_fifteen"),
        ("app_fifteen", "0032_app_fifteen"),
        ("app_fifteen", "0033_app_fifteen"),
        ("app_fifteen", "0034_app_fifteen"),
        ("app_fifteen", "0035_app_fifteen"),
        ("app_fifteen", "0036_app_fifteen"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_three", "0001_squashed_initial"),
        ("app_thirteen", "0001_squashed_initial"),
        ("app_seventeen", "0001_squashed_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelFourtyTwo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ModelFourtyThree",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ModelFourtyOne",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ModelFourtyFour",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
    ]
