# Generated by Django 3.1.8 on 2021-04-16 18:18
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # ("app_thirteen", "0007_auto_20210416_1202"),
    ]

    operations = []
