# Generated by Django 3.1.8 on 2021-04-20 18:42
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_thirteen", "0007_auto_20210416_1202"),
        ("app_fifteen", "0001_initial"),
        # ("app_seventeen", "0010_add_initial_timesheets"),
    ]

    operations = []
