# Generated by Django 3.1.8 on 2021-05-06 18:46
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fifteen", "0002_app_fifteen"),
    ]

    operations = []
