# Generated by Django 3.1.8 on 2021-05-07 22:17
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ("app_seventeen", "0018_auto_20210506_1617"),
        ("app_fifteen", "0003_app_fifteen"),
    ]

    operations = []
