# Generated by Django 3.1.8 on 2021-05-07 23:08
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fifteen", "0004_app_fifteen"),
        # ("app_seventeen", "0018_auto_20210506_1617"),
    ]

    operations = []
