# Generated by Django 3.1.8 on 2021-05-08 00:27
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fifteen", "0005_app_fifteen"),
    ]

    operations = []
