# Generated by Django 3.1.11 on 2021-05-26 22:38
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fifteen", "0007_app_fifteen"),
    ]

    operations = []
