# Generated by Django 3.1.11 on 2021-06-01 15:20
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_seventeen", "0023_auto_20210525_1758"),
        ("app_fifteen", "0009_app_fifteen"),
    ]

    operations = []
