# Generated by Django 3.1.12 on 2021-06-22 16:01
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fifteen", "0011_app_fifteen"),
    ]

    operations = []
