# Generated by Django 3.1.13 on 2021-07-15 21:02
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fifteen", "0013_app_fifteen"),
    ]

    operations = []
