# Generated by Django 3.1.13 on 2021-11-16 22:45
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fifteen", "0014_app_fifteen"),
    ]

    operations = []
