# Generated by Django 3.1.13 on 2021-12-03 19:47
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_seventeen", "0034_auto_20211115_1710"),
        ("app_fifteen", "0015_app_fifteen"),
    ]

    operations = []
