# Generated by Django 3.1.13 on 2021-12-03 21:26
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fifteen", "0016_app_fifteen"),
    ]

    operations = []
