# Generated by Django 3.1.13 on 2021-12-03 21:34
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fifteen", "0018_app_fifteen"),
    ]

    operations = []
