# Generated by Django 3.1.13 on 2021-12-22 19:31
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fifteen", "0022_app_fifteen"),
    ]

    operations = []
