# Generated by Django 3.1.14 on 2022-02-17 20:59
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fifteen", "0023_app_fifteen"),
    ]

    operations = []
