# Generated by Django 3.2.13 on 2022-06-14 21:47
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_seventeen", "0037_switch_to_pay_periods"),
        ("app_fifteen", "0025_app_fifteen"),
    ]

    operations = []
