# Generated by Django 3.2.15 on 2022-09-08 17:38
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fifteen", "0026_app_fifteen"),
        # ("app_seventeen", "0047_auto_20220908_1517"),
    ]

    operations = []
