# Generated by Django 3.2.16 on 2022-10-07 20:25
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_thirteen", "0025_auto_20220414_1451"),
        ("app_fifteen", "0027_app_fifteen"),
    ]

    # run_before = (
    #     ("app_four", "0009_auto_20220916_1201"),
    #     ("app_nine", "0015_remove_timesheetsimport_pay_period_ending"),
    #     ("app_eleven", "0011_remove_recentlyapprovedreportdownload_pay_period_ending"),
    #     ("app_seventeen", "0049_auto_20220916_1201"),
    # )

    operations = []
