# Generated by Django 3.2.19 on 2023-08-14 15:53
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fifteen", "0029_app_fifteen"),
    ]

    operations = []
