# Generated by Django 3.2.20 on 2023-10-03 17:07
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fifteen", "0030_app_fifteen"),
    ]

    operations = []
