# Generated by Django 4.2.11 on 2024-04-12 17:26
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_three", "0006_auto_20210622_1210"),
        ("app_fifteen", "0031_app_fifteen"),
    ]

    operations = []
