# Generated by Django 4.2.11 on 2024-05-28 20:24
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fifteen", "0032_app_fifteen"),
    ]

    operations = []
