# Generated by Django 4.2.17 on 2025-01-09 17:01
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fifteen", "0033_app_fifteen"),
    ]

    operations = []
