# Generated by Django 3.1.11 on 2021-05-31 23:23
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_two", "0002_app_two"),
    ]

    operations = []
