# Generated by Django 3.1.11 on 2021-06-03 22:53
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_ten", "0001_initial"),
    ]

    operations = []
