# Generated by Django 3.1.12 on 2021-06-04 16:13
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_five", "0001_initial"),
    ]

    operations = []
