# Generated by Django 3.1.8 on 2021-04-28 23:24
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # ("app_thirteen", "0010_remove_project_label"),
    ]

    operations = []
