# Generated by Django 4.2.21 on 2025-09-11 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("app_twelve", "0001_initial"),
        ("app_twelve", "0002_app_twelve"),
        ("app_twelve", "0003_app_twelve"),
        ("app_twelve", "0004_app_twelve"),
        ("app_twelve", "0005_app_twelve"),
        ("app_twelve", "0006_app_twelve"),
        ("app_twelve", "0007_app_twelve"),
        ("app_twelve", "0008_app_twelve"),
        ("app_twelve", "0009_app_twelve"),
        ("app_twelve", "0010_app_twelve"),
        (
            "app_twelve",
            "0011_app_twelve",
        ),
        ("app_twelve", "0012_app_twelve"),
        ("app_twelve", "0013_app_twelve"),
        ("app_twelve", "0014_app_twelve"),
        ("app_twelve", "0015_app_twelve"),
        ("app_twelve", "0016_app_twelve"),
        ("app_twelve", "0017_app_twelve"),
        ("app_twelve", "0018_app_twelve"),
        ("app_twelve", "0019_app_twelve"),
        ("app_twelve", "0020_app_twelve"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_eighteen", "0001_squashed_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelTwentySix",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("sort_order", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ModelTwentySeven",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_categories",
                        to="app_twelve.modeltwentysix",
                    ),
                ),
                (
                    "work_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_categories",
                        to="app_eighteen.modelfiftyfour",
                    ),
                ),
            ],
            options={
                "ordering": ("phase", "work_category"),
                "verbose_name": "project category",
                "verbose_name_plural": "project categories",
                "unique_together": {("phase", "work_category")},
            },
        ),
        migrations.CreateModel(
            name="ModelTwentyEight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_work_activities",
                        to="app_eighteen.modelfiftyfive",
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("one", "One"),
                            ("two", "Two"),
                        ],
                        max_length=1024,
                        verbose_name="type",
                    ),
                ),
                (
                    "project_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_work_activities",
                        to="app_twelve.modeltwentyseven",
                    ),
                ),
            ],
            options={
                "ordering": ("project_category", "work_activity"),
                "verbose_name": "work activity",
                "verbose_name_plural": "work activities",
            },
        ),
        migrations.AlterUniqueTogether(
            name="modeltwentyeight",
            unique_together={("project_category", "work_activity")},
        ),
        migrations.CreateModel(
            name="ModelTwentyNine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_eleven",
                    models.CharField(
                        choices=[
                            ("one", "One"),
                            ("two", "Two"),
                        ],
                        max_length=1024,
                    ),
                ),
                ("effective", models.DateField()),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_twelve.modeltwentysix",
                    ),
                ),
            ],
            options={
                "ordering": ("-effective",),
                "default_related_name": "phase_status_history",
                "unique_together": {("phase", "effective")},
            },
        ),
        migrations.CreateModel(
            name="ModelTwentyFive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField()),
            ],
            options={
                "db_table": "app_twelve_phasedata",
                "managed": False,
                "default_related_name": "phase_data",
            },
        ),
    ]
