# Generated by Django 3.1.8 on 2021-04-29 22:02
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_twelve", "0001_initial"),
    ]

    operations = []
