# Generated by Django 4.2.21 on 2025-09-11 17:30
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("app_twelve", "0001_initial"),
        ("app_twelve", "0002_app_twelve"),
        ("app_twelve", "0003_app_twelve"),
        ("app_twelve", "0004_app_twelve"),
        ("app_twelve", "0005_app_twelve"),
        ("app_twelve", "0006_app_twelve"),
        ("app_twelve", "0007_app_twelve"),
        ("app_twelve", "0008_app_twelve"),
        ("app_twelve", "0009_app_twelve"),
        ("app_twelve", "0010_app_twelve"),
        (
            "app_twelve",
            "0011_app_twelve",
        ),
        ("app_twelve", "0012_app_twelve"),
        ("app_twelve", "0013_app_twelve"),
        ("app_twelve", "0014_app_twelve"),
        ("app_twelve", "0015_app_twelve"),
        ("app_twelve", "0016_app_twelve"),
        ("app_twelve", "0017_app_twelve"),
        ("app_twelve", "0018_app_twelve"),
        ("app_twelve", "0019_app_twelve"),
        ("app_twelve", "0020_app_twelve"),
    ]

    dependencies = [
        ("app_thirteen", "0001_squashed_initial"),
        ("app_twelve", "0001_squashed_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modeltwentysix",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phases",
                to="app_thirteen.modelthirtyone",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="modeltwentysix",
            options={"ordering": ("project", "sort_order")},
        ),
        migrations.AlterUniqueTogether(
            name="modeltwentysix",
            unique_together={("project", "name")},
        ),
    ]
