# Generated by Django 4.2.21 on 2025-09-11 17:30
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("app_twelve", "0001_initial"),
        ("app_twelve", "0002_app_twelve"),
        ("app_twelve", "0003_app_twelve"),
    ]

    dependencies = [
        ("app_thirteen", "0001_squashed_initial"),
        ("app_twelve", "0001_squashed_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modeltwentysix",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phases",
                to="app_thirteen.modelthirtyone",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="modeltwentysix",
            options={"ordering": ("project", "sort_order")},
        ),
        migrations.AlterUniqueTogether(
            name="modeltwentysix",
            unique_together={("project", "name")},
        ),
    ]
