# Generated by Django 3.1.8 on 2021-04-30 18:32
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_thirteen", "0010_remove_project_label"),
        ("app_twelve", "0002_app_twelve"),
    ]

    operations = []
