# Generated by Django 3.1.8 on 2021-05-05 16:55
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_twelve", "0003_app_twelve"),
        # Create and populate the field after `0015_populate_timesheet_task_task` creates the tasks
        # ("app_seventeen", "0015_populate_timesheet_task_task"),
    ]

    operations = []
