# Generated by Django 3.1.8 on 2021-05-05 16:55
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_twelve", "0004_app_twelve"),
    ]

    operations = []
