# Generated by Django 3.1.8 on 2021-05-07 21:02
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_twelve", "0005_app_twelve"),
    ]

    operations = []
