# Generated by Django 3.1.11 on 2021-05-18 20:07
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_twelve", "0006_app_twelve"),
    ]

    operations = []
