# Generated by Django 3.1.11 on 2021-05-21 23:32
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_eighteen", "0001_initial"),
        # ("app_eighteen", "0003_auto_20210525_1737"),
        # ("app_seventeen", "0021_timesheettask_party_leader"),
        ("app_twelve", "0007_app_twelve"),
    ]

    operations = []
