# Generated by Django 3.1.11 on 2021-05-28 00:45
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_twelve", "0008_app_twelve"),
    ]

    operations = []
