# Generated by Django 3.1.12 on 2021-06-08 18:20
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_thirteen", "0016_historicalproject"),
        # ("app_eighteen", "0004_historicalsoftware_historicalworkactivity_historicalworkcategory"),
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_twelve", "0010_app_twelve"),
    ]

    operations = []
