# Generated by Django 3.1.12 on 2021-06-08 20:52
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_twelve",
            "0011_app_twelve",
        ),
    ]

    operations = []
