# Generated by Django 3.1.12 on 2021-06-09 17:10
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_eighteen", "0004_historicalsoftware_historicalworkactivity_historicalworkcategory"),
        ("app_twelve", "0012_app_twelve"),
    ]

    operations = []
