# Generated by Django 3.2.13 on 2022-04-21 17:28
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_twelve", "0013_app_twelve"),
    ]

    operations = []
