# Generated by Django 3.2.22 on 2023-10-13 21:51
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_twelve", "0016_app_twelve"),
    ]

    operations = []
