# Generated by Django 3.2.22 on 2023-10-20 22:15
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_twelve", "0018_app_twelve"),
    ]

    operations = []
