# Generated by Django 3.1.13 on 2021-11-18 21:37
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # ("app_nine", "0004_auto_20211117_1454"),
    ]

    operations = []
