# Generated by Django 3.1.13 on 2021-11-20 00:15
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_fourteen", "0001_initial"),
    ]

    operations = []
