# Generated by Django 3.1.13 on 2021-12-06 18:58
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_nine", "0011_auto_20211206_1158"),
        ("app_fourteen", "0003_app_fourteen"),
    ]

    operations = []
