# Generated by Django 4.2.21 on 2025-09-11 22:17

import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("users", "0001_initial"),
        ("users", "0002_users"),
        ("users", "0003_users"),
        ("users", "0004_users"),
    ]

    dependencies = [
        ("users", "0001_squashed_initial"),
        ("app_three", "0001_squashed_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelFiftyTwo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
    ]
