# Generated by Django 4.2.21 on 2025-09-11 22:17

import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("users", "0001_initial"),
        ("users", "0002_users"),
        ("users", "0003_users"),
        ("users", "0004_users"),
        ("users", "0005_users"),
        ("users", "0006_users"),
        ("users", "0007_users_2"),
        ("users", "0007_users"),
        ("users", "0008_users"),
        ("users", "0009_users"),
        ("users", "0010_users"),
        ("users", "0011_users"),
        ("users", "0012_users"),
        ("users", "0013_users"),
        ("users", "0014_users"),
        ("users", "0015_users"),
        ("users", "0016_users"),
        ("users", "0017_users"),
        ("users", "0018_users"),
        ("users", "0019_users_2"),
        ("users", "0019_users"),
        ("users", "0020_users"),
        ("users", "0021_users"),
        ("users", "0022_users"),
        ("users", "0023_users"),
        ("users", "0024_users"),
        ("users", "0025_users_2"),
        ("users", "0025_users"),
        ("users", "0026_users"),
        ("users", "0027_users"),
        ("users", "0028_users"),
        ("users", "0029_users"),
        ("users", "0030_users"),
        ("users", "0031_users"),
        ("users", "0032_users"),
        ("users", "0033_users"),
        ("users", "0034_users"),
        ("users", "0035_users"),
        ("users", "0036_users"),
        (
            "users",
            "0037_users",
        ),
        ("users", "0038_users"),
        ("users", "0039_users"),
        ("users", "0040_users"),
        ("users", "0041_users"),
        ("users", "0042_users"),
        ("users", "0043_users"),
    ]

    dependencies = [
        ("users", "0001_squashed_initial"),
        ("app_three", "0001_squashed_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelFiftyTwo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
    ]
