# Generated by Django 3.1.8 on 2021-05-04 17:00
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_users"),
        # ("auth", "0012_alter_user_first_name_max_length"),
        # ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = []
