# Generated by Django 3.1.8 on 2021-05-05 20:31
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_users"),
        # ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = []
