# Generated by Django 3.1.8 on 2021-05-08 16:55
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_users"),
    ]

    operations = []
