# Generated by Django 3.1.8 on 2021-05-12 15:12
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_users"),
    ]

    operations = []
