# Generated by Django 3.1.8 on 2021-05-12 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_users_2"),
        ("users", "0007_users"),
    ]

    operations = []
