# Generated by Django 3.1.8 on 2021-05-12 19:45
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_users"),
    ]

    operations = []
