# Generated by Django 3.1.11 on 2021-05-14 21:24
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_users"),
    ]

    operations = []
