# Generated by Django 3.1.11 on 2021-05-17 23:12
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_users"),
    ]

    operations = []
