# Generated by Django 3.1.11 on 2021-05-18 00:16
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_users"),
    ]

    operations = []
