# Generated by Django 3.1.11 on 2021-05-26 19:59
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_users"),
        # ("app_one", "0001_initial"),
        # ("app_eighteen", "0003_auto_20210525_1737"),
    ]

    operations = []
