# Generated by Django 3.1.11 on 2021-05-27 23:56
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_twelve", "0008_auto_20210521_1732"),
        ("users", "0013_users"),
    ]

    operations = []
