# Generated by Django 3.1.11 on 2021-05-28 00:36
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_users"),
    ]

    operations = []
