# Generated by Django 3.1.12 on 2021-06-04 23:39
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_users"),
    ]

    operations = []
