# Generated by Django 3.1.12 on 2021-06-07 19:56
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_users"),
    ]

    operations = []
