# Generated by Django 3.1.12 on 2021-06-09 15:33
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_users"),
        ("users", "0019_users_2"),
    ]

    operations = []
