# Generated by Django 3.1.12 on 2021-06-09 17:02
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_three", "0002_remove_email_reviewed_tasks_notification"),
        ("users", "0020_users"),
    ]

    operations = []
