# Generated by Django 3.1.12 on 2021-06-22 15:55
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_three", "0003_auto_20210622_0953"),
        ("users", "0021_users"),
    ]

    operations = []
