# Generated by Django 3.1.12 on 2021-06-22 22:13
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_users"),
    ]

    operations = []
