# Generated by Django 3.1.12 on 2021-06-23 18:55
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_sixteen", "0001_initial"),
        ("users", "0024_users"),
    ]

    operations = []
