# Generated by Django 3.1.12 on 2021-06-24 17:28
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_users"),
    ]

    operations = []
