# Generated by Django 3.1.12 on 2021-06-24 20:40
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_users"),
        ("users", "0025_users_2"),
    ]

    operations = []
