# Generated by Django 3.1.13 on 2021-07-06 22:38
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_users"),
    ]

    operations = []
