# Generated by Django 3.1.13 on 2021-07-14 14:37
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_users"),
    ]

    operations = []
