# Generated by Django 3.1.13 on 2021-07-20 16:33
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_users"),
    ]

    operations = []
