# Generated by Django 3.1.13 on 2021-08-04 15:59
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_users"),
    ]

    operations = []
