# Generated by Django 3.1.13 on 2021-08-13 14:24
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_eight", "0001_initial"),
        ("users", "0031_users"),
    ]

    operations = []
