# Generated by Django 3.1.13 on 2021-08-11 21:29
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_users"),
    ]

    operations = []
