# Generated by Django 3.1.13 on 2021-08-13 22:25
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0033_users"),
    ]

    operations = []
