# Generated by Django 3.1.13 on 2021-11-25 23:27
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0035_users"),
    ]

    operations = []
