# Generated by Django 3.1.13 on 2021-12-01 21:07
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0036_users"),
    ]

    operations = []
