# Generated by Django 3.2.13 on 2022-07-06 15:52
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0038_users"),
    ]

    operations = []
