# Generated by Django 3.2.15 on 2022-08-12 21:17
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0039_users"),
    ]

    operations = []
