# Generated by Django 4.2.11 on 2024-04-12 17:27
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0042_users"),
    ]

    operations = []
