# Generated by Django 4.2.21 on 2025-09-11 16:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("app_eight", "0001_initial"),
        ("app_eight", "0002_app_eight"),
        ("app_eight", "0003_app_eight"),
        ("app_eight", "0004_app_eight"),
        ("app_eight", "0005_app_eight"),
        ("app_eight", "0006_app_eight"),
        ("app_eight", "0007_app_eight"),
    ]

    dependencies = [
        ("app_six", "0001_squashed_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelFourteen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
    ]
