# Generated by Django 3.1.13 on 2021-08-13 16:53
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ("app_six", "0007_historicalemployee"),
        ("app_eight", "0002_app_eight"),
    ]

    operations = []
