# Generated by Django 3.1.13 on 2021-08-13 16:54
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_eight", "0003_app_eight"),
    ]

    operations = []
