# Generated by Django 3.1.13 on 2021-09-23 20:59
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_eight", "0004_app_eight"),
    ]

    operations = []
