# Generated by Django 3.1.13 on 2022-01-10 22:41
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_eight", "0005_app_eight"),
    ]

    operations = []
