# Generated by Django 4.2.21 on 2025-09-11 16:48
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("app_seven", "0001_initial"),
        ("app_seven", "0004_app_seven"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelThirteen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
    ]
