# Generated by Django 3.1.12 on 2021-06-24 15:48
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_seven", "0001_initial"),
    ]

    operations = []
