# Generated by Django 4.2.21 on 2025-09-11 18:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("app_thirteen", "0001_initial"),
        ("app_thirteen", "0002_app_thirteen"),
        ("app_thirteen", "0003_app_thirteen"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_two", "0001_squashed_initial"),
        ("app_six", "0001_squashed_initial"),
    ]

    run_before = [
        ("app_twelve", "0001_squashed_initial"),
        ("app_eighteen", "0001_squashed_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelThirtyOne",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("full_number", models.CharField(max_length=1024, unique=True)),
                (
                    "senior_project_leads",
                    models.ManyToManyField(
                        limit_choices_to={"is_senior_project_lead": True},
                        related_name="projects_as_senior_project_lead",
                        to="app_six.modelnine",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="app_two.modeltwo",
                    ),
                ),
                (
                    "party_leaders",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"is_party_leader": True},
                        related_name="projects_as_party_leader",
                        to="app_six.modelnine",
                    ),
                ),
                ("is_australian", models.BooleanField(default=False)),
                ("non_billable", models.BooleanField(default=False)),
            ],
            options={"ordering": ("-full_number",)},
        ),
        migrations.CreateModel(
            name="ModelThirtyTwo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_eleven",
                    models.CharField(
                        choices=[
                            ("one", "One"),
                            ("two", "Two"),
                        ],
                        max_length=1024,
                    ),
                ),
                ("effective", models.DateField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_thirteen.modelthirtyone",
                    ),
                ),
            ],
            options={
                "default_related_name": "project_status_history",
                "ordering": ("-effective",),
            },
        ),
        migrations.AlterUniqueTogether(
            name="modelthirtytwo",
            unique_together={("project", "effective")},
        ),
        migrations.CreateModel(
            name="ModelThirty",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "app_thirteen_projectdata",
                "managed": False,
                "default_related_name": "project_data",
            },
        ),
    ]
