# Generated by Django 4.2.21 on 2025-09-11 18:52
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("app_thirteen", "0001_initial"),
        ("app_thirteen", "0002_app_thirteen"),
        ("app_thirteen", "0003_app_thirteen"),
    ]

    dependencies = [
        ("app_thirteen", "0001_squashed_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_eighteen", "0001_squashed_initial"),
    ]

    operations = []
