# Generated by Django 4.2.21 on 2025-09-11 18:52
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("app_thirteen", "0001_initial"),
        ("app_thirteen", "0002_app_thirteen"),
        ("app_thirteen", "0003_app_thirteen"),
        ("app_thirteen", "0004_app_thirteen"),
        ("app_thirteen", "0005_app_thirteen"),
        ("app_thirteen", "0006_app_thirteen"),
        ("app_thirteen", "0007_app_thirteen_2"),
        ("app_thirteen", "0008_app_thirteen_2"),
        ("app_thirteen", "0007_app_thirteen"),
        ("app_thirteen", "0008_app_thirteen"),
        ("app_thirteen", "0009_app_thirteen"),
        ("app_thirteen", "0010_app_thirteen"),
        ("app_thirteen", "0011_app_thirteen"),
        ("app_thirteen", "0012_app_thirteen"),
        ("app_thirteen", "0013_app_thirteen"),
        ("app_thirteen", "0014_app_thirteen"),
        ("app_thirteen", "0015_app_thirteen"),
        ("app_thirteen", "0016_app_thirteen"),
        ("app_thirteen", "0017_app_thirteen"),
        ("app_thirteen", "0018_app_thirteen"),
        ("app_thirteen", "0019_app_thirteen"),
        ("app_thirteen", "0020_app_thirteen"),
        ("app_thirteen", "0021_app_thirteen"),
        ("app_thirteen", "0022_app_thirteen"),
        ("app_thirteen", "0023_app_thirteen"),
        ("app_thirteen", "0024_app_thirteen"),
        ("app_thirteen", "0025_app_thirteen"),
        ("app_thirteen", "0026_app_thirteen"),
        ("app_thirteen", "0027_app_thirteen"),
        ("app_thirteen", "0028_app_thirteen"),
        ("app_thirteen", "0029_app_thirteen"),
        ("app_thirteen", "0030_app_thirteen"),
        ("app_thirteen", "0031_app_thirteen"),
        ("app_thirteen", "0032_app_thirteen"),
    ]

    dependencies = [
        ("app_thirteen", "0001_squashed_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_two", "0001_squashed_initial"),
        ("app_six", "0001_squashed_initial"),
        ("app_twelve", "0002_squashed_initial"),
        ("app_eighteen", "0001_squashed_initial"),
    ]

    operations = []
