# Generated by Django 4.2.21 on 2025-09-11 20:31
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_thirteen", "0002_squashed_initial"),
    ]

    operations = []
