# Generated by Django 3.1.8 on 2021-04-15 19:27
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_six", "0003_auto_20210329_1700"),
        ("app_thirteen", "0004_app_thirteen"),
    ]

    operations = []
