# Generated by Django 3.1.8 on 2021-04-16 18:02
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_thirteen", "0006_app_thirteen"),
    ]

    operations = []
