# Generated by Django 3.1.8 on 2021-04-20 22:32
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_thirteen", "0007_app_thirteen_2"),
    ]

    operations = []
