# Generated by Django 3.1.8 on 2021-04-20 23:20
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_thirteen", "0008_app_thirteen_2"),
        ("app_thirteen", "0008_app_thirteen"),
    ]

    operations = []
