# Generated by Django 3.1.8 on 2021-04-26 22:13
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_thirteen", "0009_app_thirteen"),
    ]

    operations = []
