# Generated by Django 3.1.8 on 2021-05-12 20:52
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_six", "0005_auto_20210512_1437"),
        ("app_thirteen", "0010_app_thirteen"),
    ]

    operations = []
