# Generated by Django 3.1.11 on 2021-05-18 23:05
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_thirteen", "0011_app_thirteen"),
    ]

    operations = []
