# Generated by Django 3.1.11 on 2021-05-27 16:51
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_six", "0006_populate_employee_responsibilities"),
        ("app_thirteen", "0012_app_thirteen"),
    ]

    operations = []
