# Generated by Django 3.1.11 on 2021-05-27 16:55
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_twelve", "0007_auto_20210518_1407"),
        ("app_thirteen", "0013_app_thirteen"),
    ]

    operations = []
