# Generated by Django 3.1.11 on 2021-05-31 23:34
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_two", "0003_auto_20210531_1723"),
        ("app_thirteen", "0014_app_thirteen"),
    ]

    operations = []
