# Generated by Django 3.1.12 on 2021-06-08 18:20
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_two", "0004_historicalclient"),
        # ("app_six", "0007_historicalemployee"),
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_thirteen", "0015_app_thirteen"),
    ]

    operations = []
