# Generated by Django 3.1.12 on 2021-06-10 20:39
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_six", "0007_historicalemployee"),
        ("app_thirteen", "0016_app_thirteen"),
    ]

    operations = []
