# Generated by Django 3.1.12 on 2021-06-10 20:58
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_thirteen", "0018_app_thirteen"),
    ]

    operations = []
