# Generated by Django 3.1.13 on 2021-08-12 19:21
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_thirteen", "0019_app_thirteen"),
    ]

    operations = []
