# Generated by Django 3.1.13 on 2021-11-16 22:34
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_thirteen", "0020_app_thirteen"),
    ]

    operations = []
