# Generated by Django 3.2.13 on 2022-04-12 21:26
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_thirteen", "0023_app_thirteen"),
    ]

    operations = []
