# Generated by Django 3.2.13 on 2022-04-14 20:51
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_thirteen", "0024_app_thirteen"),
    ]

    operations = []
