# Generated by Django 3.2.16 on 2022-10-19 19:17
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_thirteen", "0025_app_thirteen"),
    ]

    operations = []
