# Generated by Django 3.2.22 on 2023-10-13 20:11
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_thirteen", "0026_app_thirteen"),
    ]

    operations = []
