# Generated by Django 3.2.22 on 2023-10-13 21:52
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_thirteen", "0027_app_thirteen"),
    ]

    operations = []
