# Generated by Django 3.2.22 on 2023-10-20 22:09
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_thirteen", "0028_app_thirteen"),
    ]

    operations = []
