# Generated by Django 4.2.11 on 2024-04-12 17:26
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_thirteen", "0029_app_thirteen"),
    ]

    operations = []
