# Generated by Django 4.2.17 on 2025-01-07 20:47
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_thirteen", "0030_app_thirteen"),
    ]

    operations = []
