# Generated by Django 4.2.21 on 2025-09-10 22:25
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("app_one", "0001_initial"),
        ("app_one", "0002_app_one"),
        ("app_one", "0003_app_one"),
        ("app_one", "0004_app_one"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_eighteen", "0001_squashed_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelOne",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
    ]
