# Generated by Django 3.1.11 on 2021-05-25 22:16
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_eighteen", "0003_auto_20210525_1737"),
        ("app_one", "0001_initial"),
    ]

    operations = []
