# Generated by Django 3.2.16 on 2022-10-19 19:17
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_one", "0003_app_one"),
    ]

    operations = []
