# Generated by Django 4.2.21 on 2025-09-11 17:26
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("app_eleven", "0001_initial"),
        ("app_eleven", "0002_app_eleven"),
        ("app_eleven", "0003_app_eleven"),
        ("app_eleven", "0004_app_eleven"),
        ("app_eleven", "0005_app_eleven"),
        ("app_eleven", "0006_app_eleven"),
        ("app_eleven", "0007_app_eleven"),
        ("app_eleven", "0008_app_eleven"),
        ("app_eleven", "0009_app_eleven"),
        ("app_eleven", "0010_app_eleven"),
        ("app_eleven", "0011_app_eleven"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_seventeen", "0001_squashed_initial"),
    ]

    run_before = [
        ("app_nine", "0001_squashed_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelTwentyTwo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ModelTwentyOne",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ModelTwentyThree",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ModelTwentyFour",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
    ]
