# Generated by Django 3.1.13 on 2021-07-06 22:12
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ("app_seventeen", "0027_auto_20210624_1237"),
    ]

    operations = []
