# Generated by Django 3.1.13 on 2021-07-06 23:26
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_eleven", "0001_initial"),
    ]

    operations = []
