# Generated by Django 3.1.13 on 2021-07-15 20:47
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("app_seventeen", "0029_auto_20210708_0935"),
        ("app_eleven", "0002_app_eleven"),
    ]

    operations = []
