# Generated by Django 3.1.13 on 2021-07-19 17:55
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_eleven", "0003_app_eleven"),
        # ("app_thirteen", "0019_auto_20210610_1458"),
        # ("app_seventeen", "0029_auto_20210708_0935"),
    ]

    operations = []
