# Generated by Django 3.1.13 on 2021-07-19 23:28
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ("app_seventeen", "0030_auto_20210719_1728"),
        ("app_eleven", "0004_app_eleven"),
    ]

    operations = []
