# Generated by Django 3.1.13 on 2021-08-13 22:16
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_eleven", "0005_app_eleven"),
    ]

    operations = []
