# Generated by Django 3.1.13 on 2021-11-17 22:03
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_eleven", "0006_app_eleven"),
    ]

    operations = []
